# Generated by Django 4.2.1 on 2023-06-01 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('abiturient', '0001_initial'),
        ('specialty', '0001_initial'),
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('application_date', models.DateField()),
                ('status', models.CharField(max_length=255)),
                ('abiturient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abiturient.abiturient')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exam')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specialty.specialty')),
            ],
        ),
    ]
